### ISSUE TITLE
Arabic translation 

### ISSUE THREAD

**Issue by TChi91** [go-gorm/gorm.io#227]
Hello , i'll be very happy if you allow me to help to translate the gorm documentation in Arabic

**Comment by jinzhu** [comment]
Hello, thank you, will add it after I finish the v2 document writing.

**Comment by TChi91** [comment]
thanks @jinzhu , in this case i will translate the v2 of the documentation, right ?

**Comment by jinzhu** [comment]
> thanks @jinzhu , in this case i will translate the v2 of the documentation, right ?

Yes

**Comment by TChi91** [comment]
thanks for giving me the chance, i'm waiting :muscle:

**Comment by jinzhu** [comment]
Added https://translate.gorm.io/project/go-gorm/ar

Thank you ;)
