### ISSUE TITLE
how to translate for v2 doc ?

### ISSUE THREAD

**Issue by uta-mori** [go-gorm/gorm.io#240]
## Your Question

I'd like to do a Japanese translation of the v2 documentation site.
What is the best way to contribute?

## Expected answer

pull request
or crowdin 
or  Should I wait a bit?

**Comment by jinzhu** [comment]
thank you for your request, will setup crowdin this week.

**Comment by jinzhu** [comment]
translate it here https://translate.gorm.io, thank you ;)
