### ISSUE TITLE
[Question] Primary Key tag is camel or snake case?

### ISSUE THREAD

**Issue by RonnanSouza** [go-gorm/gorm.io#286]
## Document Link

https://gorm.io/docs/composite_primary_key.html

## Your Question

Along all docs pages that I visited to set primary key is described as adding the `gorm:"primaryKey"` label to the struct, but here only worked after I changed to `gorm:"primary_key"`. Just to be clear: I changed camel to snake case.

**Comment by jinzhu** [comment]
GORM v2 use `primaryKey`
