### ISSUE TITLE
Add documentation on how to create a uuid field in a struct model (preferrably pgcrypto)

### ISSUE THREAD

**Issue by jawadcode** [go-gorm/gorm.io#290]

**Comment by jinzhu** [comment]
https://gorm.io/docs/data_types.html#Scanner-Valuer

**Comment by jinzhu** [comment]
https://github.com/go-gorm/gorm/blob/master/tests/postgres_test.go

**Comment by jawadcode** [comment]
Thank you but should it not be a little clearer on gorm.io how to do this?
