### ISSUE TITLE
[New Translation] Spanish associations.md

### ISSUE THREAD

**Issue by Juandavid716** [go-gorm/gorm.io#325]
## Request New Translation

* Language Name: Spanish
* Language Code: es-ES
* Disqus Lang Code: es

Please only request to translate a new language if you are a GORM & Golang user at least one year, and can translate at least 40% of documents

Thank you.

**Comment by jinzhu** [comment]
Hello @Juandavid716 

It is added, please translate it from here, https://translate.gorm.io/project/go-gorm/es-ES

Thank you.
