### ISSUE TITLE
How I can handle tables Has One to a table [Question] 

### ISSUE THREAD

**Issue by tuyendev** [go-gorm/gorm.io#343]
## Document Link
[https://gorm.io/docs/has_one.html#Self-Referential-Has-One](url)

## Your Question
Following the document, we have a simple case for **has-one relationship** like below

    // User has one CreditCard, CreditCardID is the foreign key
    type User struct {
      gorm.Model
      CreditCard CreditCard
    }
    
    type CreditCard struct {
      gorm.Model
      Number string
      UserID uint
    }

I'm starting concern what if we have 2 tables contain **has-one relationship** like

    type Teacher struct {
      gorm.Model
      CreditCard CreditCard
    }
    
    type Student struct {
      gorm.Model
      CreditCard CreditCard
    }
    
    type CreditCard struct {
      gorm.Model
      Number string
      TeacherId uint
      StudentId uint
    }

Let's say each time we create a teacher or a student, we also need to create their credit cards. So with current implementation, how we can solve it? Thank you.

**Comment by jinzhu** [comment]
https://gorm.io/docs/has_one.html#Polymorphism-Association
