### ISSUE TITLE
[Question] please document the fact that gorm:query_option is no longer supported in v2

### ISSUE THREAD

**Issue by urisimchoni** [go-gorm/gorm.io#403]
## Document Link

https://gorm.io/docs/v2_release_note.html

## Your Question

In v1.0, I've used gorm:query_option to do a locking read, as in:
```
db = db.Set("gorm:query_option", "FOR UPDATE")
db.Where("ID = ?", id).First(&customer)
```

This still compiles in v2 but has no effect and leads to subtle bugs.

## Expected answer

Please add this issue to the migration guide and point to the documentation on locking reads.

**Comment by jinzhu** [comment]
this feature is not documented in v1, so it is not mentioned in the release note.
