### ISSUE TITLE
[Question] In the new version, should we be using primary_key or primaryKey

### ISSUE THREAD

**Issue by praveenvaltix** [go-gorm/gorm.io#419]
## Your Question

We use gorm to manage our MySQL based tables. We recently upgraded to new gorm version and noticed "unique_index" was not working. We fixed our code to change it to "uniqueIndex". At the same time, we noticed that "primary_key" was still working for our tables where we use composite primary keys. 

## Expected answer

Please let us know is this expected, working accidentally and/or will be deprecated towards "primaryKey" in future?

**Comment by jinzhu** [comment]
should use `primaryKey`, `primary_key ` is already deprecated.
