### ISSUE TITLE
BUG: There's a wrong link on the website

### ISSUE THREAD

**Issue by sgkul2000** [go-gorm/gorm.io#426]
## Wrong link at "https://gorm.io/community.html"

under video examples there an anchor tag that should (at least that what I think) lead to.a youtube video about gorm tutorial but instead it has a link to a section in the same page (href="#contribute").

File to be changed: "https://github.com/go-gorm/gorm.io/blob/master/pages/community.md" under "##videos"

**Comment by s-takehana** [comment]
Fixed by f4d43df.
