### ISSUE TITLE
[Feature] Dark theme

### ISSUE THREAD

**Issue by devdammit** [go-gorm/gorm.io#441]
## Describe the feature

Adding a dark theme with the ability to switch to a light one. By default, the selected system theme is expected

## Motivation

I, like many other programmers, use a dark theme in development and surfing. I think that many people will be grateful to read the documentation in a convenient environment for them

---
UPD: I can help with this if there is any help with the design or other help :)

**Comment by jinzhu** [comment]
It would be helpful it you can add the dark theme, thank you.

**Comment by jinzhu** [comment]
Going to close this issue, PR at any time would be welcome.
