### ISSUE TITLE
[New Translation] Portuguese Brazil

### ISSUE THREAD

**Issue by silas-ss** [go-gorm/gorm.io#453]
## Request New Translation

* Language Name: Portuguese Brazil
* Language Code: pt-BR
* Disqus Lang Code: pt

I'm using GORM and Golang +-2 years on most projects.

Please only request to translate a new language if you are a GORM & Golang user at least one year, and can translate at least 40% of documents

Thank you.

**Comment by jinzhu** [comment]
Hello @silas-ss 

Added it here, https://translate.gorm.io thank you.
