### ISSUE TITLE
[Question] About New Session Mode

### ISSUE THREAD

**Issue by JokerQyou** [go-gorm/gorm.io#488]
## Document Link

[Method Chaining > New Session Mode](https://gorm.io/docs/method_chaining.html#New-Session-Mode)

## Your Question

The two examples are very confusing. Correct me if I'm wrong:

In example 2, the last query `tx.Where("age = ?", 28).Find(&users)` is incorrectly sharing the where clauses of an already-executed query (`tx.Where("age = ?", 18).Find(&users)`), because the two queries were derived from the same session (created by `tx := db.Where("name = ?", "jinzhu")`), **and because the finisher `Find()` does not reset internal state of `tx`**.

However, in example 1, all the three queries were also derived from the same `db` which has the same type (`*gorm.DB`) as `tx` in example 2. And since finishers does not reset internal state of `tx`, one would reasonably think it behaves the same for `db`. So, after the first query `db.Where("name = ?", "jinzhu").Where("age = ?", 18).Find(&users)`, `db` is no longer a "newly initialized `*gorm.DB`" (since a query has been executed on it). If that is true, how come the second query `db.Where("name = ?", "jinzhu2").Where("age = ?", 20).Find(&users)` does not share the `where` statement from the first query?

I can think of two explanations:

1. Either: finishers would reset internal state of `db` but not `tx`.
2. Or: `db` is still considered a "newly initialized `*gorm.DB`", no matter how many queries it has ran.

I kinda think explanation 2 is the correct one, but I'm no sure. Would you mind to clarify? I saw there's another user asking the same question (essentially) in comments of the documentation page, but so far nobody really answered.

**Comment by jinzhu** [comment]
Hi, yes `2` is the correct explanation, I will update the document to clarify it. 

thank you for your report.
