### ISSUE TITLE
[Question] cannot use map[string]gorm.Stmt{}

### ISSUE THREAD

**Issue by fastopencn** [go-gorm/gorm.io#587]
## gorm version
gorm.io/gorm v1.24.0
gorm.io/plugin/dbresolver v1.2.1 // indirect

## error
../../../pkg/mod/gorm.io/plugin/dbresolver@v1.2.1/dbresolver.go:139:18: cannot use map[string]gorm.Stmt{} (value of type map[string]gorm.Stmt) as type map[string]*gorm.Stmt in struct literal

**Comment by fastopencn** [comment]
commit error

**Comment by liangxu5** [comment]
I also have this problem, I solve it by updating the version of gorm.io/plugin/dbresolver to latest

**Comment by Yhooooo** [comment]
> 

Thanks!!  it works!! add 'require (gorm.io/plugin/dbresolver v1.3.0)' will be ok

**Comment by geekquad** [comment]
> > 
> 
> Thanks!! it works!! add 'require (gorm.io/plugin/dbresolver v1.3.0)' will be ok

This worked for me. Thanks!

**Comment by philomelus** [comment]
Worked for me from 1.5.0 -> 1.6.2.
