### ISSUE TITLE
[New Translation] Persian

### ISSUE THREAD

**Issue by keyvangholami** [go-gorm/gorm.io#606]
## Request New Translation

* Language Name: Persian
* Language Code: fa-IR
* Disqus Lang Code: fa

Please add the Persian language to the languages list.

Thank you.

**Comment by jinzhu** [comment]
Hi @keyvangholami 

Thank you for your contribution, just added it to https://translate.gorm.io/

Please translate it here, after translated like 10%, please create a PR to update [this file](https://github.com/go-gorm/gorm.io/blob/master/pages/_data/languages.yml) to add Persian

Thank you.
