### ISSUE TITLE
[New Translation] Hindi(India)

### ISSUE THREAD

**Issue by choudhary-Sanchit-sherawat** [go-gorm/gorm.io#612]
## Request New Translation

* Language Name: Hindi
* Language Code: hi-India
* Disqus Lang Code: hi

Please only request to translate a new language if you are a GORM & Golang user at least one year, and can translate at least 40% of documents

Thank you.

**Comment by programmer-for-good** [comment]
hi @jinzhu 

I'm using GORM and Golang +-1 years on projects.

i will give you sample for the HINDI language Translation

...

**Comment by jinzhu** [comment]
Hi @choudhary-Sanchit-sherawat @programmer-for-good 

Just added Hindi https://translate.gorm.io/project/go-gorm/hi

Thank you for your contribution, after translated it, please update [this file](https://github.com/go-gorm/gorm.io/blob/master/pages/_data/languages.yml) to add Hindi and create a PR.
