### ISSUE TITLE
[New Translation] Language Name

### ISSUE THREAD

**Issue by DeveloperVusal** [go-gorm/gorm.io#629]
## Request New Translation

* Language Name: Azerbaijani
* Language Code: az-AZ
* Disqus Lang Code: az

Thank you.

**Comment by jinzhu** [comment]
Hi @DeveloperVusal 

Thank you for your contribution, just added it to https://translate.gorm.io/

Please translate it here, after translated like 10%, please create a PR to update [this file](https://github.com/go-gorm/gorm.io/blob/master/pages/_data/languages.yml) to add Azerbaijani

Thank you.
