### ISSUE TITLE
[Question] Query data with filters on associated tables.

### ISSUE THREAD

**Issue by droslean** [go-gorm/gorm.io#675]
At first look this seems like a BUG. I am using a session with associations enabled. 

My models

```go
type Content struct {
	gorm.Model

	Metadata Metadata
	Data     string
	Domain   string
}

type Metadata struct {
	gorm.Model
	ContentID uint

	Locale         string
	Component      string
}
```

I am trying to get all contents with non-empty Metadata.Component.

```
var contents []Content
db.Preload("Metadata", "component <> ''").Find(&contents)
```

I can see in the logs that gormdb is getting all the Metadata with non-empty components, and I can confirm that this SQL query is correct. However, the `contents` slice holds ALL contents instead which makes the Preload useless. 

Is this a BUG or I am doing something wrong.

**Comment by a631807682** [comment]
This is supported, if you still have problem, you can submit an issue and a reproduction link in gorm.
https://gorm.io/docs/preload.html#Preload-with-conditions

**Comment by droslean** [comment]
@a631807682 Thanks for the response. You can see the description of the issue to reproduce it. I am doing exactly what the documentation says, but still gormdb load all the contents. I have see in the debug logs that it does the correct query, but still are `Contents` that shouldn't be based on the condition I added in Metadata.

**Comment by droslean** [comment]
@a631807682 My goal is to get all `Content` with empty `Metadata.component`. How can I achieve this? Based on the documents, it should just work with using the Preload, but it doesn't, and I am trying to figure out why.

**Comment by a631807682** [comment]
It cannot be reproduced, maybe you should update the gorm version, if there is still a problem, please provide a reproduction link.
```go

func TestGORM(t *testing.T) {
	DB.Migrator().DropTable(&Content{}, &Metadata{})
	DB.AutoMigrate(&Content{}, &Metadata{})

	contents := []Content{
		{Data: "data 1", Metadata: Metadata{Component: "not empty", Locale: "en"}},
		{Data: "data 2", Metadata: Metadata{Component: "", Locale: "zh"}},
		{Data: "data 3", Metadata: Metadata{Component: "not empty", Locale: "en"}},
	}

	DB.Create(&contents)

	var contents2 []Content
	DB.Preload("Metadata", "component <> ''").Find(&contents2)
	for i := 0; i < len(contents); i++ {
		expect := contents[i]
		got := contents2[i]

		tests.AssertObjEqual(t, expect, got, "Data", "Domain")

		if got.Data == "data 2" { // filter
			tests.AssertEqual(t, got.Metadata.ID, 0)
			tests.AssertEqual(t, got.Metadata.Component, "")
			tests.AssertEqual(t, got.Metadata.Locale, "")
			continue
		}
		tests.AssertObjEqual(t, expect.Metadata, got.Metadata, "Component", "Locale")
	}
}

```

**Comment by droslean** [comment]
@a631807682 The problem arises when I am trying to filter the `domain` on `Contents`. Instead, gormdb returns all the content for the specific domain with empty Metadata.

It seems that 

`r.db.WithContext(ctx).Preload("Metadata", "component  <> ''").Where("domain = ?", domain).Find(&contents)`

The `Preload` and the `Where` are not connected.

**Comment by droslean** [comment]
@a631807682 So it seems that I should do something like:
`r.db.WithContext(ctx).Joins("Metadata").Where("domain = ? AND component <> ''", domain).Find(&contents)`
