### ISSUE TITLE
Inefficient db writes when creating multiple child records at once

### ISSUE THREAD

**Issue by bspringston** [go-gorm/gorm.io#71]
Creating multiple "Belongs To" children records at the same time as creating the parent should execute 1 INSERT statement for all of the child records.

From the MySQL manual

INSERT statements that use VALUES syntax can insert multiple rows. To do this, include multiple lists of column values, each enclosed within parentheses and separated by commas. Example:

INSERT INTO tbl_name (a,b,c) VALUES(1,2,3),(4,5,6),(7,8,9);

**Comment by jinzhu** [comment]
Supported it in v2
